nama = input ("masukkan nama : ")
print ("selamat datang di kalkulator simpel saya")
print ("hello, " , nama)
print ("perkenalkan nama saya cindy rosemelinda")
print ("NIM : 230441100118 ")
print ("baik, apakah ada yang perlu saya bantu? ")
input ("masukkan pertanyaan : ")
panjang = int (input ("panjang balok : "))
lebar = int (input ("lebar balok : "))
tinggi = int (input ("tinggi balok : "))
volume = int (panjang * lebar * tinggi)
print ("volume balok adalah : ", volume)
